### ISSUE TITLE
build error according to the readme badge

### ISSUE THREAD

**Issue by matkoniecz** [Teester/Whats-Nearby#40]
It seems to be caused by

> The command "wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)" failed and exited with 4 during .

in https://travis-ci.org/Teester/Whats-Nearby/builds/418620604

Readme badge is in https://github.com/Teester/Whats-Nearby#whats-the-build-status

**Comment by Teester** [comment]
I triggered a new build and it is now passing.  The issue is with Codacy.  The Travis build gets their config file from their repo as recommended by their documentation.  Unfortunately, with all their users doing this, they are hitting Github's API limits, resulting in the occasional failure of the download command and hence the build.
